name: Add PRs to Org Project

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to org project
        uses: actions/add-to-project@v0.4.1
        with:
          project-url: https://github.com/orgs/TechStack-Backend/projects/1
          github-token: ${{ secrets.PROJECT_TOKEN }}